build-mash:
  stage: build
  image: debian:latest
  before_script:
    - apt-get update
    - apt-get install -y libreadline-dev
  script:
    - make
  artifacts:
    paths:
      - build/mash
    #expire_in: 1 week
