name: Build Mash via GNU Make

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential libreadline-dev

      - name: Build with make
        run: make

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mash
          path: build/mash

